var langue = (
    {
        mg : {
            cours :"Fampahafantarana",
            a_propos : "Fampahafantarana",
            recherche : "Hitady...",
            bienvenue : "Tongasoa ...",          
            categorie : "Sokajy",
            categorie_desc : "Safidio ny sokajy",
            module : "Modely",
            module_desk : "Safidio ny modely",           
            mesCours : "Ireo taranjako",
            mesCours_desk : "Hijery ireo taranjako",

            acceuil : "Fandraisana",
            position : "Adiresy",
            contacter : "Hiantso",
            commentaire : "Kaomentera",  
            noter : "Naotena",
            signaler : "Tatitra",
            business_training : "Inona i BUSINESS TRAINING?",
            definition : "BUSINESS TRAINING dia fanavaozana noforonin'ny tanora mpianatra tia ny teknolojia vaovao. ",
            langue : "Safidio ny fiteny",
            condition : "Fomba fampiasa",
            condition_test : "Ny tanjon'ity antontan-taratasy ity dia ny hamaritana ny fepetra sy ny fepetra izay amin'ny lafiny iray, izay antsoina avy eo hoe MPANOMPO, manome ny tranokala sy ny serivisy ho azon'ny mpampiasa azy, ary amin'ny lafiny iray, ny fomba izay idiran'ny mpampiasa ny tranokala sy mampiasa ny serivisy. Ny fifandraisana rehetra amin'ny tranokala dia iharan'ny fanarahana ireo fepetra ireo. Ho an'ny mpampiasa, ny fidirana tsotra amin'ny tranokalan'ny PUBLISHER amin'ity adiresy URL manaraka ity dia midika fanekena ny fepetra rehetra voalaza etsy ambany."
        },
        fr: {
            cours : "Présentation",
            a_propos : "À propos de nous",
            recherche : "Recherche...",
            bienvenue : "Bienvenue ...",
            categorie : "Categorie",
            categorie_desc : "Choisissez votre categorie ",
            module : "Module",
            module_desk : "Choisissez votre module",
            mesCours : "Mes cours",
            mesCours_desk : "Voir mes cours",

            acceuil : "Accueil",
            position : "Position",
            contacter : "Contacter",
            commentaire : "Commentaires",
            noter : "Noter",
            signaler : "Signaler",
            business_training : "C'est quoi BUSINESS TRAINING",
            definition : "BUSINESS TRAINING est une innovation crée par des jeune étudiant passionnés de nouvelle Téchnologie. ",
            langue : "Choisir votre langue",
            condition : "Condition d'utilisation",
        },
        en: {
            cours : "Présentation",
            a_propos : "About us",
            recherche : "Search...",
            bienvenue : "Welcome ...",
            categorie : "Category",
            categorie_desc : "Choose your category",
            module : "Module",
            module_desk : "Choose your module",
            mesCours : "My courses",
            mesCours_desk : "See my courses",

            acceuil : "Home",
            position : "Position",
            contacter : "Contacte",
            commentaire : "Comments",
            noter : "To note",
            signaler : "Report",
            business_training : "What is BUSINESS TRAINING",
            definition : "BUSINESS TRAINING is an innovation created by young students passionate about new technology.",
            langue : "Choose your language",
            condition : "Terms of use",
        }
    }
)
export default langue