var langue = (
    {
        mg : {
            cours :"Fianarana",
            a_propos : "Momba",
            recherche : "Hitady...",
            bienvenue : "Tongasoa ...",          
            categorie : "Sokajy",
            categorie_desc : "Safidio ny sokajy",
            module : "Modely",
            module_desk : "Safidio ny modely",           
            forum : "Fanehoan-kevitra",
            forum_desk : "Zaraio ato ny hevitrao",

            acceuil : "Fandraisana",
            liste_pharmacie : "Lisitra",
            position : "Adiresy",
            contacter : "Hiantso",
            parking : "Azo itondrana fiara",
            commentaire : "Kaomentera",  
            noter : "Naotena",
            signaler : "Tatitra",
            votre_commentaire : "Ny kaomontera anao:",
            business_training : "Inona i BUSINESS TRAINING?",
            definition : "BUSINESS TRAINING dia fanavaozana noforonin'ny tanora mpianatra tia ny teknolojia vaovao. ",
            langue : "Safidio ny fiteny",
            condition : "Fomba fampiasa",
            condition_test : "Ny tanjon'ity antontan-taratasy ity dia ny hamaritana ny fepetra sy ny fepetra izay amin'ny lafiny iray, izay antsoina avy eo hoe MPANOMPO, manome ny tranokala sy ny serivisy ho azon'ny mpampiasa azy, ary amin'ny lafiny iray, ny fomba izay idiran'ny mpampiasa ny tranokala sy mampiasa ny serivisy. Ny fifandraisana rehetra amin'ny tranokala dia iharan'ny fanarahana ireo fepetra ireo. Ho an'ny mpampiasa, ny fidirana tsotra amin'ny tranokalan'ny PUBLISHER amin'ity adiresy URL manaraka ity dia midika fanekena ny fepetra rehetra voalaza etsy ambany."
        },
        fr: {
            cours : "Cours",
            a_propos : "À propos de nous",
            recherche : "Recherche...",
            bienvenue : "Bienvenue ...",
            categorie : "Categorie",
            categorie_desc : "Choisissez votre categorie ",
            module : "Module",
            module_desk : "Choisissez votre module",
            forum : "Forum",
            forum_desk : "Donnez votre avis",

            acceuil : "Accueil",
            liste_pharmacie : "Liste",
            position : "Position",
            contacter : "Contacter",
            parking : "Parking sécurisé",
            commentaire : "Commentaires",
            noter : "Noter",
            signaler : "Signaler",
            votre_commentaire : "Votre commentaire:",
            business_training : "C'est quoi BUSINESS TRAINING",
            definition : "BUSINESS TRAINING est une innovation crée par des jeune étudiant passionnés de nouvelle Téchnologie. ",
            langue : "Choisir votre langue",
            condition : "Condition d'utilisation",
        },
        en: {
            pharmacie :"Pharmacy",
            bienvenue : "Welcome ...",   
            pharmacie_desc : "Buy your medicine",      
            medecin : "Doctor",
            medecin_desc : "Make your appointment",
            localistation : "Location",
            localistation_desk : "See your position",
            forum : "Forum",
            acceuil : "Home",
            liste_pharmacie : "list",
            position : "Position",
            contacter : "Contact",
            parking : "Secure parking",
            commentaire : "Comments",
            noter : "Score",
            signaler : "Report",
            votre_commentaire : "Your comment:",
            business_training : "What is BUSINESS TRAINING",
            definition : " BUSINESS TRAINING is an innovation created by young students passionate about new technology.",
            langue : "Choose your language",
            condition_test : "The purpose of this document is to define the terms and conditions under which on the one hand, hereinafter referred to as the PUBLISHER, makes the site and the services available on the site available to its users, and on the other hand, the way in which the user accesses the site and uses its services. Any connection to the site is subject to compliance with these conditions. For the user, the simple access to the PUBLISHER's site at the following URL address implies acceptance of all the conditions described below.",
            condition : "Terms of use",
        }
    }
)
export default langue